service: babel-example

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

functions:
  first:
    handler: handlers/first.hello
    events:
      - http:
          method: get
          path: first
          integration: lambda
          cors: true 
  second:
    handler: handlers/second.hello
    events:
      - http:
          method: get
          path: second
          integration: lambda
          cors: true 
